### ISSUE TITLE
Open nodes dump files (*.osn, *.osn.bz2)

### ISSUE THREAD

**Issue by don-vip** [iandees/josm-notes#28]
The plugin should be able to open notes dump files from this location:
http://planet.openstreetmap.org/notes/

**Comment by ToeBee** [comment]
Yeah, that would be neat, wouldn't it. However it turns out that the format of the API calls and the format of the notes dump is _completely_ different. Like, not even remotely related. Oh, except that they are both XML. So this just went from "provide a different InputStream to the parser" to "write a completely separate parser" :( 

@iandees didn't the first version of the notes dump generator produce API-like files? I seem to remember people asking for changes. Can these people be flogged now?

**Comment by iandees** [comment]
The notes dump format is what the API format should have been :).

I just pushed up a branch that adds the start of a parser for the format in #31.

**Comment by ToeBee** [comment]
Thanks for the code. I'm working on putting the parsing and API interactions of this plugin into JOSM core. I added your parsing code to that effort (ToeBee/josm@6561064) so I may or may not do work in this plugin to make use of it. We'll see how things go in core.

**Comment by ToeBee** [comment]
Cleaning out some old issues. The note support in JOSM core has supported opening dump files for several weeks now.
