### ISSUE TITLE
Flag closed/open

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [iandees/josm-notes#32]
If it have an option like: osm.notes.onlyOpen:true/false would be awesome.

**Comment by ToeBee** [comment]
This plugin is no longer used. Notes functionality was pulled into JOSM core quite a while ago. You can tell it to only download unresolved notes by setting the JOSM setting (in advanced settings) `osm.notes.daysClosed` to a value of 0. There is currently no way to filter notes once they are downloaded though. But that is a feature request that would have to be made in JOSM, not this plugin.

**Comment by erickdeoliveiraleal** [comment]
when you use the key osm.notes.daysClosed and find for some notes, it doesn't respect it.

**Comment by ToeBee** [comment]
Huh, you're right. It looks like I made a typo when transferring the notes code into JOSM core. It is actually looking for the configuration item with a key of `osm.notes.daysCloased` - note "Cloased" instead of "Closed" so if you change **that** one it should work. That should be an easy fix in JOSM though. I'll see if I can make a patch for it quick. But that will get tracked on the JOSM Trac instance.

**Comment by erickdeoliveiraleal** [comment]
I opened a issue here: https://josm.openstreetmap.de/ticket/14164
